version: "2"

services:
  db:
    image: rethinkdb:latest
    ports:
      - "28015:28015"
      - "8080:8080"
  web:
    build: containers/web
    command: python -u app.py
    ports:
      - "5000:5000"
    environment:
      - STATIC_FILES=https://raw.githubusercontent.com/googlefonts/fontbakery/master/dashboard/containers/static
    links:
      - db
  msgqueue:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
  worker:
    build: ..
    links:
      - db
    environment:
      - BROKER=msgqueue
      - NONPARALLEL_JOB_RUNS=4
  dispatcher:
    build: containers/dispatcher
    command: python dispatch-jobs.py
    environment:
      - BROKER=msgqueue
