apiVersion: batch/v1
kind: Job
metadata:
  name: job-fb-dispatcher-1
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      name: job-fb-dispatcher-1
    spec:
      containers:
      - name: c
        image: localhost:5000/fontbakery/job-fb-dispatcher-1
        env:
        - name: QUEUE
          value: job1
        - name: FONTBAKERY_LOCAL_DEVEL
          value: "1"
      restartPolicy: OnFailure
