runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: static/index.html
  upload: static/index\.html
- url: /dashboard
  static_files: static/dashboard.html
  upload: static/dashboard\.html
- url: /js
  static_dir: static/js
- url: /css
  static_dir: static/css
- url: /json
  static_dir: static/json
- url: /img
  static_dir: static/img
- url: /runchecks
  script: main.app

libraries:
- name: lxml
  version: latest

