apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: fontbakery-api
spec:
  replicas: 3
  template:
    metadata:
      labels:
        run: fontbakery-api
    spec:
      containers:
      - name: fontbakery-api
        image: gcr.io/fontbakery-168509/base-javascript:1
        ports:
        - containerPort: 3000
        workingDir: /var/javascript
        command: ["npm", "start"]
---
apiVersion: v1
kind: Service
metadata:
  name: fontbakery-api
  labels:
    run: fontbakery-api
spec:
  type: LoadBalancer
# need this for socketIO
  sessionAffinity: ClientIP
  ports:
    - port: 80
      targetPort: 3000
  selector:
    run: fontbakery-api
