apiVersion: v1
kind: Service
metadata:
  labels:
    db: rethinkdb
  name: rethinkdb-admin
spec:
# We can use `kubectl proxy` to access this, not exposing
# it to the public internet (what LoadBalancer does).
#  type: LoadBalancer
# ClusterIP is the default
  type: ClusterIP
  ports:
   - port: 8080
     targetPort: admin
  selector:
    db: rethinkdb
    role: admin
---
apiVersion: v1
kind: Service
metadata:
  labels:
    db: rethinkdb
  name: rethinkdb
spec:
  ports:
  - port: 29015
    targetPort: cluster
  selector:
    db: rethinkdb
    role: replica
---
apiVersion: v1
kind: Service
metadata:
  labels:
    db: rethinkdb
  name: rethinkdb-proxy
spec:
# I don't know why all these thing should be exposed to the internet
# I don't want to see any `LoadBalancer` despite our one web frontend.
#  type: LoadBalancer
  ports:
    - port: 28015
      targetPort: driver
  selector:
    db: rethinkdb
    role: proxy
