apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: fontbakery-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: fontbakery-api
    spec:
      containers:
      - name: fontbakery-api
        image: gcr.io/fontbakery-168509/base-javascript:23
        env:
          - name: COLLECTION_AUTH_SECRET
            value: ""
          - name: FONTBAKERY_LOG_LEVEL
            value: "DEBUG"
          - name: ENVIRONMENT_VERSION
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: ENVIRONMENT_VERSION
        ports:
        - containerPort: 3000
        # debugger chrome://inspect port if active
        # - containerPort: 9229
        workingDir: /var/javascript
        # CAUTION!
        # command: ["node", "--inspect=9229 ", "node/api.js"]
        command: ["npm", "start"]
---
apiVersion: v1
kind: Service
metadata:
  name: fontbakery-api
  labels:
    run: fontbakery-api
spec:
  type: LoadBalancer
# need this for socketIO
  sessionAffinity: ClientIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    run: fontbakery-api
