apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: fontbakery-worker-checker
spec:
  replicas: 5
  template:
    metadata:
      labels:
        run: fontbakery-worker-checker
    spec:
      containers:
      - name: fontbakery-worker-checker
        image: gcr.io/fontbakery-168509/base-python:1.03
        workingDir: /var/python
        command: ["python2",  "-u", "fontbakery-worker-checker.py"]
