apiVersion: v1
kind: Pod
metadata:
  labels:
    db: rethinkdb
    type: simple
  name: rethinkdb
spec:
  containers:
  - image: localhost:5000/fontbakery/rethinkdb-2.3.5
    name: rethinkdb
    ports:
    - containerPort: 8080
      name: admin-port
    - containerPort: 28015
      name: driver-port
    - containerPort: 29015
      name: cluster-port
    volumeMounts:
    - mountPath: /data/rethinkdb_data
      name: rethinkdb-storage
  volumes:
  - name: rethinkdb-storage
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    db: rethinkdb
  name: rethinkdb-admin
spec:
  ports:
   - port: 8080
     targetPort: 8080
  type: LoadBalancer
  selector:
    db: rethinkdb
    type: simple
---
apiVersion: v1
kind: Service
metadata:
  labels:
    db: rethinkdb
  name: rethinkdb-driver
spec:
  ports:
    - port: 28015
      targetPort: 28015
  selector:
    db: rethinkdb
    type: simple
