apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: fontbakery-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: fontbakery-api
    spec:
      containers:
      - name: fontbakery-api
        image: fontbakery/base-javascript:1
        env:
          - name: COLLECTION_AUTH_SECRET
            value: ""
          - name: FONTBAKERY_LOG_LEVEL
            value: "DEBUG"
        ports:
        - containerPort: 3000
        workingDir: /var/javascript
        command: ["npm", "start"]
---
apiVersion: v1
kind: Service
metadata:
  name: fontbakery-api
  labels:
    run: fontbakery-api
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    run: fontbakery-api
