apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: fontbakery-worker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: fontbakery-worker
    spec:
      containers:
      - name: fontbakery-worker
        image: fontbakery/base-python:1
        env:
          - name: FONTBAKERY_WORKER_LOG_LEVEL
            value: "INFO"
        workingDir: /var/python
        command: ["python3",  "-u", "worker-launcher.py"]

