apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: fontbakery-manifest-master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: fontbakery-manifest-master
        role: manifest
    spec:
      containers:
      - name: fontbakery-manifest-master
        image: fontbakery/base-javascript:1
        env:
          - name: FONTBAKERY_LOG_LEVEL
            value: "DEBUG"
        workingDir: /var/javascript
        command: ["node", "node/ManifestMaster.js"]
