apiVersion: apps/v1
kind: Deployment
metadata:
  name: fontbakery-manifest-csvupstream
spec:
  replicas: 1
  selector:
    matchLabels:
      component: fontbakery-manifest-csvupstream
  template:
    metadata:
      labels:
        component: fontbakery-manifest-csvupstream
        role: manifest
    spec:
      containers:
      - name: fontbakery-manifest-csvupstream
        image: fontbakery/base-javascript:1
        env:
          - name: FONTBAKERY_LOG_LEVEL
            value: "DEBUG"
          - name: DEVEL_FAMILY_WHITELIST
            value: "[\"ABeeZee\", \"Indie Flower\", \"Slabo\", \"Rosario\", \"Amiri\", \"Pacifico\", \"Astloch\"]"
          - name: CSV_SHEET_URL_SANDBOX
            value: https://doc-00-08-sheets.googleusercontent.com/pub/l5l039s6ni5uumqbsj9o11lmdc/u5fi8qu65t5vutaoq1f2t42b8g/1592511455000/101961686124685905596/*/1ODnp-yRYw1LrI3RTX-VZZsigPPieviE954sOsrlcx5o?gid=0&single=true&output=csv
            # use $ curl -Ls -o /dev/null -w %{url_effective} "https://my.url"
            # OLD value: https://docs.google.com/spreadsheets/d/1ODnp-yRYw1LrI3RTX-VZZsigPPieviE954sOsrlcx5o/pub?gid=0&single=true&output=csv
          - name: CSV_SHEET_URL_UPSTREAM
            value: https://docs.google.com/spreadsheets/d/1ampzD9veEdrwUMkOAJkMNkftqtv1jEygiPR0wZ6eNl8/pub?gid=0&single=true&output=csv
        workingDir: /var/javascript
        #command: ["node", "node/manifestSources/CSVSpreadsheet.js", "-p", "50051"]
        command: ["node", "--inspect=0.0.0.0:9229", "node/manifestSources/CSVSpreadsheet.js", "-p", "50051"]
      # depends directly on rabbitmq/amqp
      # wait until rabbitmq can be reached before starting the actual container
      initContainers:
        - name: init-wait-for-rabbitmq
          image: busybox
          command:
          - sh
          - "-c"
          - >
            until wget -q -O -
            http://guest:guest@$RABBITMQ_MANAGEMENT_SERVICE_HOST:$RABBITMQ_MANAGEMENT_SERVICE_PORT/api/aliveness-test/%2F;
            do echo [`date`] waiting for rabbitmq: 10s;
            sleep 10;
            done;
---
apiVersion: v1
kind: Service
metadata:
  name: fontbakery-manifest-csvupstream
  labels:
    component: fontbakery-manifest-csvupstream
spec:
  ports:
    - port: 50051
      targetPort: 50051
  selector:
    component: fontbakery-manifest-csvupstream
    role: manifest
